### ISSUE TITLE
Error 4 while trying to 'make rpm'

### ISSUE THREAD

**Issue by eliranbz** [id/kafka-el7-rpm#1]
[root@server kafka-el7-rpm-master]# make rpm
gpg --import KEYS
gpg: key 53038328: public key "Chris Douglas cdouglas@apache.org" imported
gpg: key 99369B56: public key "Neha Narkhede (Key for signing code and releases) nehanarkhede@apache.org" imported
gpg: key 99369B56: "Neha Narkhede (Key for signing code and releases) nehanarkhede@apache.org" not changed
gpg: key 575A2645: public key "Neha Narkhede (Key used for signing releases) neha.narkhede@gmail.com" imported
gpg: key 7F1183BD: public key "Joe Stein (CODE SIGNING KEY) joestein@apache.org" imported
gpg: key E0A61EEA: public key "Jun Rao junrao@gmail.com" imported
gpg: Total number processed: 6
gpg:               imported: 5  (RSA: 5)
gpg:              unchanged: 1
gpg --verify kafka_2.10-0.8.2.1.tgz.asc kafka_2.10-0.8.2.1.tgz
gpg: Signature made Thu 26 Feb 2015 05:31:17 PM EST using RSA key ID E0A61EEA
gpg: Good signature from "Jun Rao junrao@gmail.com"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7452 AFD2 2A9E FB5A BF6C  66EE AB61 F70F E0A6 1EEA
make: **\* [kafka-graphite-1.0.0.jar] Error 4

**Comment by id** [comment]
Fixed, thanks.

**Comment by eliranbz** [comment]
Yes, the KEYS was not up-to-date.

Thanks

**Comment by rinkymangal2010** [comment]
Where is the new key?
