### ISSUE TITLE
kafka-*.sh makes mkdir error message

### ISSUE THREAD

**Issue by sanori** [id/kafka-el7-rpm#4]
After installing the rpm, when I run kafka shell scripts such as `/opt/kafka/bin/kafka-topics.sh`
mkdir error occurs as follows:

```
$ /opt/kafka/bin/kafka-topics.sh --list --zookeeper localhost:2181
mkdir: cannot create directory '/opt/kafka/bin/../logs': Permission denied
```

It seems that the log directory is not properly set somewhere in the code.

Workaround: `sudo mkdir /opt/kafka/logs`

**Comment by id** [comment]
It works if you run this command as kafka user.
`sudo su - kafka; bin/kafka-topics.sh ...`

**Comment by id** [comment]
Sorry, I'm wrong.
The last fix changed this.

I'll have a look.
