### ISSUE TITLE
kafka 0.9.0.1 start errors on cent 7

### ISSUE THREAD

**Issue by dragosstoica** [id/kafka-el7-rpm#5]
Hi,

Did you manage to use this with:

KAFKA_VERSION ?= 0.9.0.1
SCALA_VERSION ?= 2.11

I get this errors at start:
# systemctl start kafka

Failed to issue method call: Unit kafka.service failed to load: Bad message. See system logs and 'systemctl status kafka.service' for details.
# systemctl status kafka

kafka.service - Kafka
   Loaded: error (Reason: Bad message)
  Drop-In: /usr/lib/systemd/system/kafka.service.d
           └─classpath.conf
   Active: inactive (dead)

Feb 19 23:53:20 kick systemd[1]: [/usr/lib/systemd/system/kafka.service.d/classpath.conf:3] Missing '='.

**Comment by id** [comment]
Will fix this soon, thanks.

**Comment by dragosstoica** [comment]
I moved classpath from /usr/lib/systemd/system/kafka.service.d/classpath.conf in /etc/sysconfig/kafka and its working fine

**Comment by dragosstoica** [comment]
[kafka.spec.txt](https://github.com/id/kafka-el7-rpm/files/139060/kafka.spec.txt)
